import * as express from 'express'
import * as React from 'react'
import { renderToString } from 'react-dom/server'
import Router from '../../framework/Router'

const app = express()

app.get('/api', (request, response) => {
    response.send({
        message: 'Hello from Node JS/ Typescript!'
    })
})

app.get('*', (request, response) => {
    let router = new Router()
    let application = router.getContent()
    let applicationHtml = renderToString(application)

    let html = `<!doctype html>
    <html>
        <head>
            <meta charset="utf-8">
            <meta http-equiv="x-ua-compatible" content="ie=edge">
            <title>Ocomis CMS</title>
            <meta name="viewport" content="width=device-width, initial-scale=1">
        </head>
        <body>
            <div id="root">${applicationHtml} (generated by server)</div>
            <script src="http://localhost:3001/client.bundle.js"></script>
        </body>
    </html>`

    response.send(html)
})

export default app
